# Generated by Django 4.2.5 on 2023-10-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('checkbox', 'Checkbox'), ('select', 'Select')], max_length=20),
        ),
    ]
